### ISSUE TITLE
Date setting not working correct

### ISSUE THREAD

**Issue by hendrik77** [sapmentors/SITreg#13]
Besides the error described in #12 - which is not there when editing the event - the entered date is not saved correctly:
- Entered "24.09.2016" 
- Date changed from the system to "23.09.2016" after hitting "Save"-Button
- Opened event to correct date, same happend
- Opened event and entered "25.09.2016" after save, correct date "24.09.2016" shows up

**Comment by gregorwolf** [comment]
I think that is a known issue reported here: [Date selected is saved as selected date minus 1 day #2](https://github.com/sapmentors/SITregOrganizer/issues/2)
