### ISSUE TITLE
SELECT Authorizations on Participant table must be restricted to allow use of ODXL

### ISSUE THREAD

**Issue by gregorwolf** [sapmentors/SITreg#4]
For the export of the participant list to Excel (XLSX) or CSV it would be the easiest to leverage the [ODXL](https://github.com/just-bi/odxl) project. But after installing the tool I've discovered that the current authorizations would allow even the annonymous user to download all participant details as SELECT authorizations are granted to the Participant table. 

The authorizations must be restricted to annonymous users and participants can only see the public information, organizers and defined co-organizers can only download participants of events there are involved in.

**Comment by rpbouman** [comment]
Hi Gregor! Thanks again for the invite, much appreciated :) I am now back for a week and if you need me I can try and help out on this issue. It noticed you already have a number of roles in place. It occurred to me in addition to locking down the data with database object privileges, it might also be a good idea to add an application privillege (https://help.sap.com/saphelp_hanaplatform/helpdata/en/4d/6ed4dc3db6423abd9f9a52a626618f/content.htm) to lock down access to the odxl service. I have never tried using those but if you like I can explore this option as well. I believe this would be a complementary measure - you would probably still need to secure things from the database end as well.

**Comment by gregorwolf** [comment]
Hi Roland,
thank you for the comment. I think we're on a good way to lock down the authorizations that users can only see what they should see. I've moved most of the SELECT privileges away from the plain tables to restricted views. Perhaps it might be worth a note in the ODXL project that users should double check the table SELECT privileges.
Best regards
Gregor

**Comment by rpbouman** [comment]
Hi Gregor! Ok - good to hear and thanks for the suggestion. Yes, I agree - ODXL doc should get some cautionary note as well as some suggestions on how to manage privileges. Best regards, and thanks again for your interest! I really appreciate you including it and I hope it will help further your project :)

**Comment by gregorwolf** [comment]
To allow the participant to update his registration information I was forced to define a wrapper hdbtablefunction and then call the update in a hdbtablefunction with "SQL SECURITY DEFINER". Because I can't provide the user read to the original table the update fails. Would be great if you can check commit b632fc5a4c83135eec1c2fa687f38ae4059b9452
