### ISSUE TITLE
"com.sap.sapmentors.sitreg.odataparticipant::participant" and "com.sap.sapmentors.sitreg.odataparticipant::organizer"

### ISSUE THREAD

**Issue by bobugeorgep** [sapmentors/SITreg#43]
When activating this project, the roles,

- "com.sap.sapmentors.sitreg.odataparticipant::participant" and
- "com.sap.sapmentors.sitreg.odataparticipant::organizer"
are not created.
With out this role, the odata is not executed and gives 403 error

Regards
Bobu

**Comment by gregorwolf** [comment]
should be fixed with f806dd82bfcedfd093d12874fa80d9d2851edad1

**Comment by bobugeorgep** [comment]
yes @gregorwolf , this fixed the issue... its working good
