### ISSUE TITLE
Registration not possible when form was called with Event# directly

### ISSUE THREAD

**Issue by CBasis** [sapmentors/SITreg#48]
Sending the registration form (e.g. Event in Frankfurt 21.10.2017) is not possible when using the direkt link to the event:

      https://sitregparticipant-a5a504e08.dispatcher.hana.ondemand.com/#/Events/30

leads to the list of registered participants [thats ok]
but the button (lower right corner) is named "Bearbeiten" / "Edit" 
instead of "Register" 
    It then leads to the empty(!) registration form and looks fine, but when saving all the entered data the processing ends with the three circles of death and never comes to an end.

When choosing the event once again from the navigation-panel out of all events .. then the button is correctly named "Register" and all work fine.   
   The name and email is already filled into the form (taken from the S-ID)

See Slack:SAPMentors#sitreg for details 
- Issue reported there by Hendrik
- Video and further descriotion by Sebastian

I tried to find the part where the logic fails in the sourcecode .. maybe in this section the wrong path is entered?
https://github.com/sapmentors/SITregParticipant/blob/f283fbc0b0ad1bc63b28f1a4443aea22e8ab25e6/webapp/view/Detail.view.xml#L96

**Comment by gregorwolf** [comment]
Move to frontend project.
