### ISSUE TITLE
Sorry, a technical error has occurred

### ISSUE THREAD

**Issue by tpowlas3** [sapmentors/SITreg#7]
when launching beta site using chrome, Safari
https://sitregparticipant-s0001142741trial.dispatcher.hanatrial.ondemand.com/
Error details
{
    "requestUri": "/destinations/HANAMDC/com/sap/sapmentors/sitreg/odataparticipant/service.xsodata/$metadata?sap-documentation=heading",
    "statusCode": 503,
    "statusText": "Service Unavailable",
    "headers": [],
    "body": "503 Service unavailable\r\n\r\n Sun Aug  7 09:24:16 2016\n"
}

**Comment by gregorwolf** [comment]
Could you please try again. I've just tested it and it worked fine for me. As the beta site is running on HCP Trial the HANA MDC is shut down every 12 hours. I start it using a cron script, but you might have hit exactly the 5 to 10 minutes outage.

**Comment by tpowlas3** [comment]
OK - the error occurs if I try to register on a browser where I have the SAP Certificate installed (Chrome, Safari, IE).  I just tried it on a browser (Pale Moon) where I do not have a SAP Certificate installed and I successfully registered.

**Comment by gregorwolf** [comment]
I've tried in Edge, Chrome, Firefox and IE 11 where I've had my S-User SAP Passport (X.509 Certificate) installed. Haven't got any issues. Have you tried to refresh the page using reload? If it works then it might be the issue that I've reported at: [Repeated call of HTML5 app causes "Sorry, a technical error occurred! Please try again later." error #6].(https://github.com/sapmentors/SITregParticipant/issues/6)

**Comment by tpowlas3** [comment]
I've tried refreshing, same error occurs.  I am using Windows 7 (yes very old)

**Comment by gregorwolf** [comment]
I've tried on Windows 7 using the SAP Passport with IE, Firefox and Chrome. No issues for me. But I had to clear the Cookies to get the request for the certificate.

**Comment by gregorwolf** [comment]
No further errors reported. Please reopen if you have issues.
